### ISSUE TITLE
own midi

### ISSUE THREAD

**Issue by Eumi** [llSourcell/AI_Composer#16]
From what i see it gets the midis from a url ..can i input my own? i tried to change the dtataset.zip but when i put in my own midis it gets error ...is it possible or is the code only able to run with the midis that are included?

**Comment by Eumi** [comment]
nevermind its the song best.mid ..that confused me ... hmm but still wondering if i can add my own midi files

**Comment by FinlayDaG33k** [comment]
What error do you get?

**Comment by rmarchant** [comment]
Here's what I get when I feed my own midi files in :

```
Parsing train...
Parsing test...
Parsing valid...
{'A': 1710,
 'AM': 1032,
 'B': 927,
 'C#': 2610,
 'D': 1107,
 'Dsus2': 261,
 'E': 2391,
 'EM': 180,
 'Edom': 3222,
 'F#': 3258,
 'F#m': 720,
 'G#': 705,
 'NONE': 36480,
 'augmented fourth': 753,
 'major second': 3417,
 'major seventh': 66,
 'major sixth': 2049,
 'major unison': 7080,
 'minor second': 87,
 'minor seventh': 315,
 'minor sixth': 471,
 'perfect fourth': 1788}
Number of chords: 22
Max Sequence length: 23546
Avg Sequence length: 23546.0
Num Sequences: 3
Combining train
Combining test
Combining valid
Model created!
Finished loading data, input dim: 57
1 runs detected
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    rnn.train_model()
  File "/qnas/multimedia/midi/AI_Composer/rnn.py", line 115, in train_model
    data = util.load_data('', time_step, config.time_batch_len, config.max_time_batches, nottingham=pickle)
  File "/qnas/multimedia/midi/AI_Composer/util.py", line 156, in load_data
    data["input_dim"] = dataset_data[0][0][0].shape[2]
IndexError: list index out of range
```
