### ISSUE TITLE
Models.rnn not found

### ISSUE THREAD

**Issue by Memes1** [llSourcell/AI_Composer#20]
i was trying this out and i got this im not good with code what am i doing wrong?
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import rnn
  File "/home/parrot/Documents/AI_Composer-master/rnn.py", line 16, in <module>
    from model import Model, NottinghamModel
  File "/home/parrot/Documents/AI_Composer-master/model.py", line 5, in <module>
    from tensorflow.models.rnn import rnn_cell
ImportError: No module named models.rnn

**Comment by huabawa** [comment]
I have the same issue

**Comment by FinlayDaG33k** [comment]
Also having this issue.  
By the looks of it they moved some stuff around in the new TensorFlow versions.
Still looking for a solution, will report back IF I find something...

**Comment by Memes1** [comment]
@FinlayDaG33k ok thank you again as I said I don't really know code but I hope you figure this out

**Comment by FinlayDaG33k** [comment]
Yea, I'm not good at code either.
I did find a solution however.
If you are on Linux (most likely you are using Ubuntu?) you need to run these commands in your Terminal:
`sudo pip uninstall tensorflow` (just uninstalling your current TF version)
`sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl`

After that, try running the script again

**Comment by Memes1** [comment]
@FinlayDaG33k ok I will try this in the morning Ty and I'm using kali

**Comment by FinlayDaG33k** [comment]
Kali and Ubuntu are pretty much the same (both Debian-based stuff blablabla), so it should work just fine.

**Comment by quintendewilde** [comment]
I've followed your steps and got following errors. 

```
quinten@quinten:~/Documents/AI_Composer$ pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
Collecting tensorflow==0.8.0 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
  Using cached https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
Collecting six>=1.10.0 (from tensorflow==0.8.0)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting numpy>=1.8.2 (from tensorflow==0.8.0)
  Using cached numpy-1.13.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting protobuf==3.0.0b2 (from tensorflow==0.8.0)
  Using cached protobuf-3.0.0b2-py2.py3-none-any.whl
Collecting wheel (from tensorflow==0.8.0)
  Using cached wheel-0.30.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf==3.0.0b2->tensorflow==0.8.0)
  Using cached setuptools-36.6.0-py2.py3-none-any.whl
Installing collected packages: six, numpy, setuptools, protobuf, wheel, tensorflow
Successfully installed numpy-1.13.3 protobuf-3.4.0 setuptools-36.6.0 six-1.11.0 tensorflow-0.8.0 wheel-0.30.0
quinten@quinten:~/Documents/AI_Composer$ 
quinten@quinten:~/Documents/AI_Composer$ python main.py
[libprotobuf FATAL google/protobuf/src/google/protobuf/stubs/common.cc:67] This program requires version 3.4.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.4.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)
Aborted (core dumped)
quinten@quinten:~/Documents/AI_Composer$ 

```

**Comment by quintendewilde** [comment]
uninstalling pip protobuf and uninstalling conda protobuf did the trick!

**Comment by sreekanth3333** [comment]
install new python environment with tensorflow 0.8 version instead of other versions
