### ISSUE TITLE
ImportError: This module is deprecated.  Use tf.nn.rnn_cell instead.

### ISSUE THREAD

**Issue by jamesalton** [llSourcell/AI_Composer#4]
james@:~/ai/AI_Composer$ python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import rnn
  File "/home/james/ai/AI_Composer/rnn.py", line 16, in <module>
    from model import Model, NottinghamModel
  File "/home/james/ai/AI_Composer/model.py", line 5, in <module>
    from tensorflow.models.rnn import rnn_cell
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/rnn_cell.py", line 21, in <module>
    raise ImportError("This module is deprecated.  Use tf.nn.rnn_cell instead.")
ImportError: This module is deprecated.  Use tf.nn.rnn_cell instead.

(Using TensorFlow binary: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0-cp27-none-linux_x86_64.whl)

I looked in /usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/rnn_cell.py and sure enough it just spits out that deprecation message. 

The relevant line in /home/james/ai/AI_Composer/model.py:

```
from tensorflow.models.rnn import rnn_cell
```

I'm too noob to all of this to figure out how to put tf.nn.rnn_cell in there instead. I tried this:

```
james@MUSSLI:~/ai/AI_Composer$ python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import rnn
  File "/home/james/ai/AI_Composer/rnn.py", line 16, in <module>
    from model import Model, NottinghamModel
  File "/home/james/ai/AI_Composer/model.py", line 5
    from tensorflow.models.rnn import tf.nn.rnn_cell
                                        ^
SyntaxError: invalid syntax
```

I tried to figure out where "tf" and "nn" are if they go in the import string somehow...

```
james@MUSSLI:/usr/local/lib/python2.7/dist-packages/tensorflow$ find . -name tf
james@MUSSLI:/usr/local/lib/python2.7/dist-packages/tensorflow$ find . -name nn
james@MUSSLI:/usr/local/lib/python2.7/dist-packages/tensorflow$ find . -name rnn_cell.py
./models/rnn/rnn_cell.py
./python/ops/rnn_cell.py
./contrib/rnn/python/ops/rnn_cell.py
```

tf and nn are not there?

**Comment by llSourcell** [comment]
Hey @jamesalton thanks for pointing this out. If you made a fix, would you be willing to make a PR? I'd merge it immediately, amount of code i have to maintain is exploding with each video lol

**Comment by ProGamerGov** [comment]
I am currently experiencing the same issue.

```
ubuntu@ubuntu-VirtualBox:~/AI_Composer$ python rnn_sample.py --config_file new_config_file.config
Traceback (most recent call last):
  File "rnn_sample.py", line 12, in <module>
    from model import Model, NottinghamModel
  File "/home/ubuntu/AI_Composer/model.py", line 5, in <module>
    from tensorflow.models.rnn import rnn_cell
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/rnn_cell.py", line 21, in <module>
    raise ImportError("This module is deprecated.  Use tf.nn.rnn_cell instead.")
ImportError: This module is deprecated.  Use tf.nn.rnn_cell instead.
ubuntu@ubuntu-VirtualBox:~/AI_Composer$ 

```

**Comment by ProGamerGov** [comment]
Following the Tensorflow install guide on this page: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md, but with the modified download link:


```
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl

sudo pip install --upgrade $TF_BINARY_URL
```

Trying to run the code results in an error:

```
ubuntu@ubuntu-VirtualBox:~/AI_Composer$ python rnn_sample.py --config_file new_config_file.config
Traceback (most recent call last):
  File "rnn_sample.py", line 13, in <module>
    from rnn import DefaultConfig
  File "/home/ubuntu/AI_Composer/rnn.py", line 12, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot
ubuntu@ubuntu-VirtualBox:~/AI_Composer$ 

```

So I install the following missing modules:

`$ pip install matplotlib`

`$ sudo apt-get install python-tk
`


Which got me to:

```
ubuntu@ubuntu-VirtualBox:~/AI_Composer$ python rnn_sample.py --config_file new_config_file.config
Traceback (most recent call last):
  File "rnn_sample.py", line 29, in <module>
    with open(args.config_file, 'r') as f: 
IOError: [Errno 2] No such file or directory: 'new_config_file.config'
ubuntu@ubuntu-VirtualBox:~/AI_Composer$
```

**Comment by ProGamerGov** [comment]
I have created PR with the changes.

**Comment by llSourcell** [comment]
@ProGamerGov you're my hero thank you

**Comment by DerekQQQ** [comment]
can't generate music 

```
`Traceback` (most recent call last):
  File "rnn_sample.py", line 58, in <module>
    saver.restore(session, model_path)
  File "/home/derek/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1088, in restore
    raise ValueError("Restore called with invalid save path %s" % save_path)
ValueError: Restore called with invalid save path F5PTV3HFEGJA.model

```

**Comment by iantheconway** [comment]
I found that if I change the two lines line model.py from:

from tensorflow.models.rnn import rnn_cell
from tensorflow.models.rnn import rnn, seq2seq

to:
from tensorflow.python.ops import rnn_cell
from tensorflow.python.ops import rnn, seq2seq

It seems to work fine (although so far I've only done training), and I don't have to revert to an earlier version of Tensorflow.

@llSourcell I can make a pull request if you're interested.

**Comment by iantheconway** [comment]
It seems I spoke too soon on this issue; my Tensorflow was not on the latest version, and it there are numerous differences in the Tensorflow 1.0 API that are causing issues.
